travis:
  secure:
    BINSTAR_TOKEN: WNlVa6RyVWMjf3mEk4bVYHX/OBJYuEdMumjEfvRV4qwZbwbZ0R19LWoqHGmht9nEVRle5i7hqx38+j7zYEByKvBK1YMY1YnaEvHOAf9TnDkt+JhX7jXR0Uf9ZUpZuSLY/SDZoJaigBVwlWIEgx3pZQvmuXbjz1SvWoPiKcaSmbKyCZYpPeBZzoiCwqtFb8ot8UYm/Nim5EIN0g+SWbGeUvmbzDehV2UQBAKjny5K4XmfBWE1nhHUmRT4mAbZ3NKGHCqjG+ppRwqHhKPX/qc1Ai/wW+y2lNmfDjGbNpOFG/d4v6JG6VruRKCXT5tKazk5+k0g2dy7J6M53f6V6JWqc8VyH+OVSlK9Shlz6+GTQEkGP7jbIhnGnTiEgvLotF/GVmYngpGmcInkFMIfvYScLTGthFQP3c2jqq5CnQTQzobi4QaCz4EW7nbeOIKWq+HWXEQ61nIIf1L8Ax6efLx9aXUh7Dn8jgM+humGIuoKFmH3tdtE97J6Tts+rJuAjPW6dyZ+hecawa5tjfaPmrgUqM9KF7K472MA59A6mms6/VqGhfOytq4T1LQY8SnvrSFzBmC/HMl/irxG/B5wF8vyqf6oQ/+UFWbBkx/KTUPeFM5xZjp9x29DkLX2xLK/5ULLijPVpCJFDfdo8EDu94uWPrI+OwLxZkizrXDN1bBkmU0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
